filter:
    paths:
        - 'lib/*.php'
        - 'tests/*.php'
tools:
    php_mess_detector: true
    php_cs_fixer:
        config:
            level: psr2
    php_code_sniffer:
        config:
            standard: PSR2
    sensiolabs_security_checker: true
    php_hhvm: true
    php_cpd: true
    php_pdepend: true
    external_code_coverage: true
    php_analyzer: true
