language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install: composer selfupdate
install: composer install
before_script: mkdir -p build/coverage
script: ./vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml
after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/coverage/clover.xml
