language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install: composer selfupdate
install: composer install
before_script: mkdir -p build/coverage
script: ./vendor/bin/phpunit --coverage-clover=build/coverage/clover.xml
after_success:
  - composer require scrutinizer/ocular:~1.1.0
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/coverage/clover.xml
